# Site settings
title: CASI
description: 'Centro Acadêmico de Sistemas de Informação'
url: 'centroacademico.github.io'
baseurl: '/'
google_analytics: 'UA-114541288-1'
disqus_shortname: 'centroacademico-github-io'

author:
  name: 'CASI'
  email: centro.academico.casi@gmail.com
  twitter_username: 
  facebook_username: 
  github_username:  centroacademico
  linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
